name: Test Action

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      
      - name: Download MFW-CA
        if: matrix.os != 'android'
        id : download_mfw-ca
        uses: robinraju/release-downloader@v1
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-${{ matrix.os }}-${{ matrix.arch }}*"
          latest: true
          out-file-path: "MFW"
          extract: true
      
      
      - name: Create test icon
        shell: powershell
        run: |
          Write-Host "Creating test icon..."
          
          # Create a proper 16x16 icon file (valid .ico format)
          # This is a minimal valid .ico file with a 16x16 blue square
          $iconBytes = [System.Convert]::FromBase64String("AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///z////8/////P////z////8/////P////z////8/////P////z////8/////PwAAAAAAAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z//////////////////////////////////////////////////////////////////////P////z8AAAAAAAAAAP///z////8/////P////z////8/////P////z////8/////P////z////8/////PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAA=")
          
          [System.IO.File]::WriteAllBytes("$PWD\test.ico", $iconBytes)
          
          if (Test-Path "test.ico") {
            Write-Host "✅ Test icon created"
            $size = (Get-Item "test.ico").Length
            Write-Host "   Icon file size: $size bytes"
          } else {
            Write-Error "❌ Failed to create test icon"
            exit 1
          }
      
      - name: Test icon replacement
        uses: ./
        with:
          exe-path: 'MFW/MFW.exe'
          icon-path: 'test.ico'
          output-path: 'MFW/test_modified.exe'
      
      - name: Verify output
        shell: powershell
        run: |
          if (Test-Path "test_modified.exe") {
            Write-Host "✅ Modified executable exists"
            $size = (Get-Item "test_modified.exe").Length
            Write-Host "   File size: $size bytes"
          } else {
            Write-Error "❌ Modified executable not found"
            exit 1
          }
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "MFW"
            
